version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean install
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/SAMExclusions-app-jar-with-dependencies.jar
  discard-paths: yes
