package com.sam.exclusion.service;

public final class Constants {
    public static final String[] searchList = {
            ", DDS",
            ", LLC",
            ", P.J.S.",
            ", & STOVALL",
            ", (F/K/A JONES FESTUS DEVELOPMENT",
            ", A",
            ", A",
            ", A CALIFORNIA CORP",
            ", A CHIROPRACTIC CORPORATION",
            ", A CORPORATION",
            ", A MEDICAL CORP",
            ", A MEDICAL CORPORATION",
            ", A MEDICAL PARTNERSHIP",
            ", A PROFESSIONAL MEDICAL CORPORATION",
            ", A RESTRICTED PROFESSIONAL BENEFIT COMPANY",
            ", A TEXAS LIMITED LIABILITY COMPANY",
            ", A.C.",
            ", A.S.",
            ", AB",
            ", ACTIVIDAD AUXILIAR DEL CREDITO S.A. DE C.V.",
            ", ACTIVIDAD DEL CREDITO",
            ", ADMINISTRATION FOR THE BUILDING OF MOSQUES",
            ", AERONAUTICA",
            ", AKA TASOS",
            ", ALEXANDER",
            ", ALINA S",
            ", AL-JAHRA",
            ", AMRELI",
            ", AND ANIMAL WEALTH",
            ", AND BUJANOVAC",
            ", AND CONSULTANT GROUP",
            ", AND EXPORT OF HIGH TECH PRODUCTS ROSTEC",
            ", AND GENERAL SHIPPING LIMITED LIABILITY COMPANY",
            ", AND GENERAL SHIPPING LIMITED LIABILITY PRIVATE COMPANY",
            ", AND GENERAL SHIPPING/ LIMITED LIABILITY",
            ", AND RESEARCH",
            ", AND SECURITY SERVICES",
            ", AND STUDIES",
            ", AND TO CREATE SOCIETY - SIRAT",
            ", ANO",
            ", AO",
            ", AO AKB",
            ", AP",
            ", ARMANDO",
            ", ARMANDO JIMENEZ",
            ", ASOCIACION CIVIL",
            ", AUDITING",
            ", BANCO UNIVERSAL",
            ", BANCO UNIVERSAL C.A.",
            ", BANCO UNIVERSAL CA",
            ", BARRY DC",
            ", BEOGRAD STARI GRAD",
            ", BHR",
            ", BOSNIA AND HERZEGOVINA",
            ", BOYD",
            ", BRADFORD T MD PA",
            ", BRADY ISLAND FACILITY",
            ", BRIAN",
            ", BRIAN VALLERINO",
            ", C.A.",
            ", C.C.",
            ", C.S.W.",
            ", CANTU",
            ", CARL & DONALD INC",
            ", CASA DE CAMBIO",
            ", CHARLES E M D P",
            ", CHECHNYA (SOBR)",
            ", CHILD AND FAMILY SERVICES",
            ", CHINESE ACADEMY OF SCIENCES CAPITAL CONSTRUCTION",
            ", CHOW AND CHU",
            ", CIRCULARES Y ORTOGONALES",
            ", CJSC",
            ", CLINTON C. JR.",
            ", CLOSED JOINT-STOCK COMPANY",
            ", CO",
            ", CO.",
            ", COMBUSTIBLES Y LUBRICANTES",
            ", CONCEPT",
            ", CORP",
            ", CORP.",
            ", CPA & ASSOCIATES",
            ", CPO",
            ", CRAIG",
            ", CRIMEA STATE AVIATION ENTERPRISE",
            ", CULTURAL",
            ", CULTURE AND BUILDING SOCIETY - SIRAT",
            ", D C",
            ", D C",
            ", D D S",
            ", D M D",
            ", D O",
            ", D P M",
            ", D. C.",
            ", D. D. S.",
            ", D. O.",
            ", D.C.",
            ", D.C.",
            ", D.D.D.",
            ", D.D.S.",
            ", D.D.S.",
            ", D.M.D.",
            ", D.O.",
            ", D.O.",
            ", D.P.M.",
            ", D.V.M.",
            ", D/B/A CULLIGAN OF SPRINGFIELD",
            ", DAVID",
            ", DBA DUNCAN DRUGS",
            ", DBA FAMILY CARE PHARMACY",
            ", DBA MIDAS",
            ", DBA NOBLE E&C",
            ", DC",
            ", DC",
            ", DDS",
            ", DDS",
            ", DE LA CLASE OBRERA",
            ", DEBORAH L",
            ", DEL",
            ", DELORES",
            ", DENNIS B DDS",
            ", DMD",
            ", DMD",
            ", DO",
            ", DOCHERNEE OBSHCHESTVO S OGRANICHENNOI OTVETSTVENNOSTYU",
            ", DON",
            ", DON",
            ", DOUGLAS",
            ", DP",
            ", DPM",
            ", DPM",
            ", DPM P C",
            ", DR DON",
            ", DR WIT A INTERNAL MEDICINE",
            ", DR.",
            ", DRUG STORE",
            ", DUBAI",
            ", EDWIN AND ASSOCIATES",
            ", EDWIN AND EDWIN",
            ", ELECTRONICS & MEDIA PRINTING CO. LTD.",
            ", ENGINEERING",
            ", ENVIRONMENTAL",
            ", FACS",
            ", FELTON & MINKUS",
            ", FORMERLY KMCO PROPERTIES LP",
            ", FORMERLY KMTEX PROPERTIES",
            ", G. YEKATERINBURG OAO",
            ", G.EKATERINBURG",
            ", GANDHIDHAM",
            ", GARCIA",
            ", GENERAL TRADE",
            ", GEOFIZIKI I MINERALNOGO SYRYA",
            ", GERARD FRANCIS",
            ", GOA",
            ", GONDA",
            ", GP",
            ", GUARD AND SECURITY SERVICES",
            ", GUARDING",
            ", GUARDING AND SECURITY SERVICES",
            ", GUJ",
            ", GUP",
            ", GUP RK",
            ", HAJI ABDUL BASEER MONEY CHANGER",
            ", I.G.",
            ", II",
            ", III",
            ", III",
            ", III BAYNARD",
            ", IN",
            ", IN.",
            ", INC",
            ", INC",
            ", INC",
            ", INC DBA GARRETT WAKATO OLUBO MSPT",
            ", INC DBA NOBLE E&C",
            ", INC.",
            ", INC.",
            ", INC. (SCR)",
            ", INC. AKA FINCH HILL WATER COMPANY",
            ", INC. ALSO DBA RKB FACILITY SOLUTIONS",
            ", INC. D/B/A DIAL A MAID",
            ", INC. D/B/A ZIP IT DRY CLEANERS",
            ", INC. DBA CAPE COD ICE",
            ", INC. OF SUFFOLK",
            ", INC. RETIREMENT PLAN",
            ", INCORPORATED",
            ", INDIANA",
            ", INMOBILIARIA Y CONSTRUCCION DE OBRAS",
            ", INTER",
            ", INTL.",
            ", INV",
            ", IRGC (PASDARAN)",
            ", ITS OFFICERS",
            ", IV",
            ", JEFFERSON A. AND JEFFERSON T.",
            ", JOINT STOCK COMPANY",
            ", JOINT-STOCK COMPANY",
            ", JOYCE",
            ", JR",
            ", JR.",
            ", JR.",
            ", JR. GONZALEZ PIZANA",
            ", JR. M.D",
            ", JSC",
            ", K.K.",
            ", KEENAN R",
            ", KENNETH JAMES",
            ", KEVIN J",
            ", KIM",
            ", KING",
            ", KRIMTETS",
            ", KRYMSKE RESPUBLIKANSKE PIDPRYEMSTVO",
            ", L",
            ", L L C",
            ", L. C.",
            ", L.C.",
            ", L.L.C",
            ", L.L.C.",
            ", L.P.",
            ", L.T.D.",
            ", LAW OFFICE OF",
            ", LC",
            ", LESTER EARL EARL ANDERSON",
            ", LIMITED",
            ", LIMITED (D/B/A)",
            ", LIMITED LIABILITY COMPANY",
            ", LLC",
            ", LLC",
            ", LLC",
            ", LLC DBA VICTOR TORRES CONSTRUCTION",
            ", LLC (GTS)",
            ", LLC (USA)",
            ", LLC D/B/A GREEN WORKS HOLDINGS",
            ", LLC DBA HEARNS ENTERPRISES",
            ", LLC DBA HUSSEY COPPER",
            ", LLC DBA MIDAS",
            ", LLC DBA NOLAN MANUFACTURING CO.",
            ", LLC DBA NOLAN MFG. CO. - ELECTRONICS DIVISION",
            ", LLC USA",
            ", LLC)",
            ", LLC.",
            ", LLLP",
            ", LLP",
            ", LP",
            ", LTD",
            ", LTD LCC",
            ", LTD.",
            ", LTD. CHINA PINGMEI SHENMA GROUP",
            ", LTD. NANCHANG BRANCH",
            ", LTD._IT DIVISION",
            ", M D",
            ", M S",
            ", M.D.",
            ", M.D.",
            ", M.D. AND ASSOCIATES",
            ", M.D. P.",
            ", M.S.",
            ", M.S.",
            ", MADHUBANI",
            ", MANUFACTURE",
            ", MD",
            ", MD",
            ", MD PA",
            ", MD PLLC",
            ", MD.",
            ", MD.",
            ", MDS",
            ", MEDIA",
            ", MEDICAL CO",
            ", MEDVEDJA",
            ", MERCADO EXTERIOR",
            ", MH",
            ", MICHAEL A",
            ", MONTENEGRO",
            ", MUJER Y COMUNAS",
            ", MUJER Y COMUNIAS",
            ", MUMBAI",
            ", MUREADA",
            ", N.J.",
            ", NATIONAL PRODUCTION AND AGRARIAN UNION",
            ", NEW DELHI",
            ", NOSE AND THROAT",
            ", O.",
            ", OAO",
            ", OD",
            ", OJSC",
            ", OOO",
            ", OPEN JOINT STOCK COMPANY",
            ", OPEN JOINT-STOCK COMPANY",
            ", ORANGE",
            ", ORTHOTIC & PEDORTHIC ASSOCIATES",
            ", OTKRYTOE AKTSIONERNOE OBSCHCHESTVO",
            ", OTKRYTOE AKTSIONERNOE OBSHCHESTVO",
            ", P",
            ", P A",
            ", P C",
            ", P.",
            ", P. A.",
            ", P. C.",
            ", P.A.",
            ", P.C.",
            ", P.C. AND ASSOCIATES",
            ", P.J.S.",
            ", P.L.C.",
            ", P.L.L.C.",
            ", P.S.",
            ", PA",
            ", PA",
            ", PAO",
            ", PARQUE DE SANTA MARIA HOUSING DEVELOPMENT",
            ", PAT",
            ", PC",
            ", PC - SOUTHGATE",
            ", PC.",
            ", PH. D. PSYCHOLOGIST",
            ", PH.D",
            ", PH.D.",
            ", PH.D. AND ASSOCIATES",
            ", PIETRACK AND ASSOCIATES",
            ", PJSC",
            ", PJSC (UKRAINE)",
            ", PL.L.C.",
            ", PLC",
            ", PLLC",
            ", PPLC",
            ", PRODUCTION AND EXPORT OF ADVANCED TECHNOLOGY INDUSTRIAL PRODUCT",
            ", PRODUCTION AND EXPORT OF ADVANCED TECHNOLOGY INDUSTRIAL PRODUCT ROSTEKHNOLOGII",
            ", PROFESSIONAL ASSOCIATION",
            ", PROFESSIONAL CHIROPRACTIC CORPORATION",
            ", PROFESSIONAL DENTAL CORP.",
            ", PROMET I USLUGE MELVALE CORPORATION DOO",
            ", PROPAGANDA AND AGITATION DEPARTMENT",
            ", PRYVATNE AT",
            ", PS",
            ", PS",
            ", PUBLIC JOINT STOCK COMPANY",
            ", PUERTO RICO",
            ", R AND DC",
            ", R&DC",
            ", RALPH",
            ", RAY",
            ", RESEARCH",
            ", ROBERT D. AND ASSOCIATES",
            ", ROBERT T JR MD",
            ", ROSHELL",
            ", RUSSIAN ACADEMY OF SCIENCES",
            ", S C",
            ", S DE R.L. DE CV",
            ", S K MD INC",
            ", S. DE P.R. DE R.L.",
            ", S. DE P.R. DE R.L. DE C.V.",
            ", S. DE R.L. DE C.V.",
            ", S.A.",
            ", S.A.",
            ", S.A. (GTI)",
            ", S.A. DE C. V.",
            ", S.A. DE C.V",
            ", S.A. DE C.V.",
            ", S.A. DE C.V.",
            ", S.A. DE C.V. FARMACIA JERLYNE",
            ", S.A.C.",
            ", S.A.C.A.",
            ", S.A.P.I. DE C.V.",
            ", S.A.R.L.",
            ", S.C.",
            ", S.C. DE R.L. DE C.V.",
            ", S.P.R. DE R.I.",
            ", S.R.O.",
            ", SA",
            ", SADRA",
            ", SAL",
            ", SC",
            ", SCOTT L",
            ", SERVICIOS Y MANTENIMIENTOS C.A.",
            ", SHARJAH",
            ", SOCIEDAD ANOMINA DE CAPITAL VARIABLE",
            ", SOCIEDAD ANONIMA",
            ", SOCIEDAD ANONIMA DE CAPITAL VARIABLE",
            ", SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA",
            ", SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA",
            ", SOCIETY OF THE REBIRTH OF THE ISLAMIC PEOPLE",
            ", SPINE SURGERY",
            ", SPRL",
            ", SR",
            ", SR.",
            ", SR.",
            ", SRI LANKA",
            ", STATE RESEARCH AND PRODUCTION ENTERPRISE BAZALT",
            ", STEPHENS",
            ", SUBSIDIARIES AND DIVISIONS",
            ", SUPPORT AND PROCUREMENT KALA NAFT COMPANY",
            ", TAYLOR",
            ", TECNICOS Y OPERATIVOS DUREL",
            ", THE",
            ", TOV",
            ", TRADE & INVESTMENT S.R.O.",
            ", TRADE AND GENERAL SERVICES LTD. / BAGHDAD",
            ", TRADE AND INVESTMENT S.R.O.",
            ", TRANSPORTATION & OIL SERVICES LTD.",
            ", TRANSPORTATION AND OIL SERVICES",
            ", TRANSPORTE",
            ", UCH",
            ", UP",
            ", UP",
            ", V.Z.W.",
            ", VISAKHAPATNAM",
            ", W.L.L.",
            ", WENDALL ALAN",
            ", Y SERVICIOS AEREOS S.A. DE C.V.",
            ", YASIR RAFEA ALI",
            ", Z",
            ", ZAKRYTOE AKTSIONERNOE OBSHCHESTVO INVESTITSIONNAYA KOMPANIYA",
            ", ZAO",
            ",110016",
            ",271308",
            ",362720",
            ",364560",
            ",370201",
            ",400023",
            ",400053",
            ",403802",
            ",530026",
            ",ARE",
            ",INC.",
            ",IND",
            ",LLC",
            ",LTD.",
            ",OOO",
            ",P.A.",
            ",PLLC"
    };

    public static final String[] replacementList = {
            " DDS",
            " LLC",
            " P.J.S.",
            " & STOVALL",
            " (F/K/A JONES FESTUS DEVELOPMENT",
            " A",
            " A",
            " A CALIFORNIA CORP",
            " A CHIROPRACTIC CORPORATION",
            " A CORPORATION",
            " A MEDICAL CORP",
            " A MEDICAL CORPORATION",
            " A MEDICAL PARTNERSHIP",
            " A PROFESSIONAL MEDICAL CORPORATION",
            " A RESTRICTED PROFESSIONAL BENEFIT COMPANY",
            " A TEXAS LIMITED LIABILITY COMPANY",
            " A.C.",
            " A.S.",
            " AB",
            " ACTIVIDAD AUXILIAR DEL CREDITO S.A. DE C.V.",
            " ACTIVIDAD DEL CREDITO",
            " ADMINISTRATION FOR THE BUILDING OF MOSQUES",
            " AERONAUTICA",
            " AKA TASOS",
            " ALEXANDER",
            " ALINA S",
            " AL-JAHRA",
            " AMRELI",
            " AND ANIMAL WEALTH",
            " AND BUJANOVAC",
            " AND CONSULTANT GROUP",
            " AND EXPORT OF HIGH TECH PRODUCTS ROSTEC",
            " AND GENERAL SHIPPING LIMITED LIABILITY COMPANY",
            " AND GENERAL SHIPPING LIMITED LIABILITY PRIVATE COMPANY",
            " AND GENERAL SHIPPING/ LIMITED LIABILITY",
            " AND RESEARCH",
            " AND SECURITY SERVICES",
            " AND STUDIES",
            " AND TO CREATE SOCIETY - SIRAT",
            " ANO",
            " AO",
            " AO AKB",
            " AP",
            " ARMANDO",
            " ARMANDO JIMENEZ",
            " ASOCIACION CIVIL",
            " AUDITING",
            " BANCO UNIVERSAL",
            " BANCO UNIVERSAL C.A.",
            " BANCO UNIVERSAL CA",
            " BARRY DC",
            " BEOGRAD STARI GRAD",
            " BHR",
            " BOSNIA AND HERZEGOVINA",
            " BOYD",
            " BRADFORD T MD PA",
            " BRADY ISLAND FACILITY",
            " BRIAN",
            " BRIAN VALLERINO",
            " C.A.",
            " C.C.",
            " C.S.W.",
            " CANTU",
            " CARL & DONALD INC",
            " CASA DE CAMBIO",
            " CHARLES E M D P",
            " CHECHNYA (SOBR)",
            " CHILD AND FAMILY SERVICES",
            " CHINESE ACADEMY OF SCIENCES CAPITAL CONSTRUCTION",
            " CHOW AND CHU",
            " CIRCULARES Y ORTOGONALES",
            " CJSC",
            " CLINTON C. JR.",
            " CLOSED JOINT-STOCK COMPANY",
            " CO",
            " CO.",
            " COMBUSTIBLES Y LUBRICANTES",
            " CONCEPT",
            " CORP",
            " CORP.",
            " CPA & ASSOCIATES",
            " CPO",
            " CRAIG",
            " CRIMEA STATE AVIATION ENTERPRISE",
            " CULTURAL",
            " CULTURE AND BUILDING SOCIETY - SIRAT",
            " D C",
            " D C",
            " D D S",
            " D M D",
            " D O",
            " D P M",
            " D. C.",
            " D. D. S.",
            " D. O.",
            " D.C.",
            " D.C.",
            " D.D.D.",
            " D.D.S.",
            " D.D.S.",
            " D.M.D.",
            " D.O.",
            " D.O.",
            " D.P.M.",
            " D.V.M.",
            " D/B/A CULLIGAN OF SPRINGFIELD",
            " DAVID",
            " DBA DUNCAN DRUGS",
            " DBA FAMILY CARE PHARMACY",
            " DBA MIDAS",
            " DBA NOBLE E&C",
            " DC",
            " DC",
            " DDS",
            " DDS",
            " DE LA CLASE OBRERA",
            " DEBORAH L",
            " DEL",
            " DELORES",
            " DENNIS B DDS",
            " DMD",
            " DMD",
            " DO",
            " DOCHERNEE OBSHCHESTVO S OGRANICHENNOI OTVETSTVENNOSTYU",
            " DON",
            " DON",
            " DOUGLAS",
            " DP",
            " DPM",
            " DPM",
            " DPM P C",
            " DR DON",
            " DR WIT A INTERNAL MEDICINE",
            " DR.",
            " DRUG STORE",
            " DUBAI",
            " EDWIN AND ASSOCIATES",
            " EDWIN AND EDWIN",
            " ELECTRONICS & MEDIA PRINTING CO. LTD.",
            " ENGINEERING",
            " ENVIRONMENTAL",
            " FACS",
            " FELTON & MINKUS",
            " FORMERLY KMCO PROPERTIES LP",
            " FORMERLY KMTEX PROPERTIES",
            " G. YEKATERINBURG OAO",
            " G.EKATERINBURG",
            " GANDHIDHAM",
            " GARCIA",
            " GENERAL TRADE",
            " GEOFIZIKI I MINERALNOGO SYRYA",
            " GERARD FRANCIS",
            " GOA",
            " GONDA",
            " GP",
            " GUARD AND SECURITY SERVICES",
            " GUARDING",
            " GUARDING AND SECURITY SERVICES",
            " GUJ",
            " GUP",
            " GUP RK",
            " HAJI ABDUL BASEER MONEY CHANGER",
            " I.G.",
            " II",
            " III",
            " III",
            " III BAYNARD",
            " IN",
            " IN.",
            " INC",
            " INC",
            " INC",
            " INC DBA GARRETT WAKATO OLUBO MSPT",
            " INC DBA NOBLE E&C",
            " INC.",
            " INC.",
            " INC. (SCR)",
            " INC. AKA FINCH HILL WATER COMPANY",
            " INC. ALSO DBA RKB FACILITY SOLUTIONS",
            " INC. D/B/A DIAL A MAID",
            " INC. D/B/A ZIP IT DRY CLEANERS",
            " INC. DBA CAPE COD ICE",
            " INC. OF SUFFOLK",
            " INC. RETIREMENT PLAN",
            " INCORPORATED",
            " INDIANA",
            " INMOBILIARIA Y CONSTRUCCION DE OBRAS",
            " INTER",
            " INTL.",
            " INV",
            " IRGC (PASDARAN)",
            " ITS OFFICERS",
            " IV",
            " JEFFERSON A. AND JEFFERSON T.",
            " JOINT STOCK COMPANY",
            " JOINT-STOCK COMPANY",
            " JOYCE",
            " JR",
            " JR.",
            " JR.",
            " JR. GONZALEZ PIZANA",
            " JR. M.D",
            " JSC",
            " K.K.",
            " KEENAN R",
            " KENNETH JAMES",
            " KEVIN J",
            " KIM",
            " KING",
            " KRIMTETS",
            " KRYMSKE RESPUBLIKANSKE PIDPRYEMSTVO",
            " L",
            " L L C",
            " L. C.",
            " L.C.",
            " L.L.C",
            " L.L.C.",
            " L.P.",
            " L.T.D.",
            " LAW OFFICE OF",
            " LC",
            " LESTER EARL EARL ANDERSON",
            " LIMITED",
            " LIMITED (D/B/A)",
            " LIMITED LIABILITY COMPANY",
            " LLC",
            " LLC",
            " LLC",
            " LLC DBA VICTOR TORRES CONSTRUCTION",
            " LLC (GTS)",
            " LLC (USA)",
            " LLC D/B/A GREEN WORKS HOLDINGS",
            " LLC DBA HEARNS ENTERPRISES",
            " LLC DBA HUSSEY COPPER",
            " LLC DBA MIDAS",
            " LLC DBA NOLAN MANUFACTURING CO.",
            " LLC DBA NOLAN MFG. CO. - ELECTRONICS DIVISION",
            " LLC USA",
            " LLC)",
            " LLC.",
            " LLLP",
            " LLP",
            " LP",
            " LTD",
            " LTD LCC",
            " LTD.",
            " LTD. CHINA PINGMEI SHENMA GROUP",
            " LTD. NANCHANG BRANCH",
            " LTD._IT DIVISION",
            " M D",
            " M S",
            " M.D.",
            " M.D.",
            " M.D. AND ASSOCIATES",
            " M.D. P.",
            " M.S.",
            " M.S.",
            " MADHUBANI",
            " MANUFACTURE",
            " MD",
            " MD",
            " MD PA",
            " MD PLLC",
            " MD.",
            " MD.",
            " MDS",
            " MEDIA",
            " MEDICAL CO",
            " MEDVEDJA",
            " MERCADO EXTERIOR",
            " MH",
            " MICHAEL A",
            " MONTENEGRO",
            " MUJER Y COMUNAS",
            " MUJER Y COMUNIAS",
            " MUMBAI",
            " MUREADA",
            " N.J.",
            " NATIONAL PRODUCTION AND AGRARIAN UNION",
            " NEW DELHI",
            " NOSE AND THROAT",
            " O.",
            " OAO",
            " OD",
            " OJSC",
            " OOO",
            " OPEN JOINT STOCK COMPANY",
            " OPEN JOINT-STOCK COMPANY",
            " ORANGE",
            " ORTHOTIC & PEDORTHIC ASSOCIATES",
            " OTKRYTOE AKTSIONERNOE OBSCHCHESTVO",
            " OTKRYTOE AKTSIONERNOE OBSHCHESTVO",
            " P",
            " P A",
            " P C",
            " P.",
            " P. A.",
            " P. C.",
            " P.A.",
            " P.C.",
            " P.C. AND ASSOCIATES",
            " P.J.S.",
            " P.L.C.",
            " P.L.L.C.",
            " P.S.",
            " PA",
            " PA",
            " PAO",
            " PARQUE DE SANTA MARIA HOUSING DEVELOPMENT",
            " PAT",
            " PC",
            " PC - SOUTHGATE",
            " PC.",
            " PH. D. PSYCHOLOGIST",
            " PH.D",
            " PH.D.",
            " PH.D. AND ASSOCIATES",
            " PIETRACK AND ASSOCIATES",
            " PJSC",
            " PJSC (UKRAINE)",
            " PL.L.C.",
            " PLC",
            " PLLC",
            " PPLC",
            " PRODUCTION AND EXPORT OF ADVANCED TECHNOLOGY INDUSTRIAL PRODUCT",
            " PRODUCTION AND EXPORT OF ADVANCED TECHNOLOGY INDUSTRIAL PRODUCT ROSTEKHNOLOGII",
            " PROFESSIONAL ASSOCIATION",
            " PROFESSIONAL CHIROPRACTIC CORPORATION",
            " PROFESSIONAL DENTAL CORP.",
            " PROMET I USLUGE MELVALE CORPORATION DOO",
            " PROPAGANDA AND AGITATION DEPARTMENT",
            " PRYVATNE AT",
            " PS",
            " PS",
            " PUBLIC JOINT STOCK COMPANY",
            " PUERTO RICO",
            " R AND DC",
            " R&DC",
            " RALPH",
            " RAY",
            " RESEARCH",
            " ROBERT D. AND ASSOCIATES",
            " ROBERT T JR MD",
            " ROSHELL",
            " RUSSIAN ACADEMY OF SCIENCES",
            " S C",
            " S DE R.L. DE CV",
            " S K MD INC",
            " S. DE P.R. DE R.L.",
            " S. DE P.R. DE R.L. DE C.V.",
            " S. DE R.L. DE C.V.",
            " S.A.",
            " S.A.",
            " S.A. (GTI)",
            " S.A. DE C. V.",
            " S.A. DE C.V",
            " S.A. DE C.V.",
            " S.A. DE C.V.",
            " S.A. DE C.V. FARMACIA JERLYNE",
            " S.A.C.",
            " S.A.C.A.",
            " S.A.P.I. DE C.V.",
            " S.A.R.L.",
            " S.C.",
            " S.C. DE R.L. DE C.V.",
            " S.P.R. DE R.I.",
            " S.R.O.",
            " SA",
            " SADRA",
            " SAL",
            " SC",
            " SCOTT L",
            " SERVICIOS Y MANTENIMIENTOS C.A.",
            " SHARJAH",
            " SOCIEDAD ANOMINA DE CAPITAL VARIABLE",
            " SOCIEDAD ANONIMA",
            " SOCIEDAD ANONIMA DE CAPITAL VARIABLE",
            " SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA",
            " SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA",
            " SOCIETY OF THE REBIRTH OF THE ISLAMIC PEOPLE",
            " SPINE SURGERY",
            " SPRL",
            " SR",
            " SR.",
            " SR.",
            " SRI LANKA",
            " STATE RESEARCH AND PRODUCTION ENTERPRISE BAZALT",
            " STEPHENS",
            " SUBSIDIARIES AND DIVISIONS",
            " SUPPORT AND PROCUREMENT KALA NAFT COMPANY",
            " TAYLOR",
            " TECNICOS Y OPERATIVOS DUREL",
            " THE",
            " TOV",
            " TRADE & INVESTMENT S.R.O.",
            " TRADE AND GENERAL SERVICES LTD. / BAGHDAD",
            " TRADE AND INVESTMENT S.R.O.",
            " TRANSPORTATION & OIL SERVICES LTD.",
            " TRANSPORTATION AND OIL SERVICES",
            " TRANSPORTE",
            " UCH",
            " UP",
            " UP",
            " V.Z.W.",
            " VISAKHAPATNAM",
            " W.L.L.",
            " WENDALL ALAN",
            " Y SERVICIOS AEREOS S.A. DE C.V.",
            " YASIR RAFEA ALI",
            " Z",
            " ZAKRYTOE AKTSIONERNOE OBSHCHESTVO INVESTITSIONNAYA KOMPANIYA",
            " ZAO",
            "110016",
            "271308",
            "362720",
            "364560",
            "370201",
            "400023",
            "400053",
            "403802",
            "530026",
            "ARE",
            "INC.",
            "IND",
            "LLC",
            "LTD.",
            "OOO",
            "P.A.",
            "PLLC"
    };
}
