package com.sam.exclusion.util;

public final class Constants {
    public static final String[] searchList = {
            ", & STOVALL",
            ", (F/K/A JONES FESTUS DEVELOPMENT",
            ", A CALIFORNIA CORP",
            ", A CHIROPRACTIC CORPORATION",
            ", A CORPORATION",
            ", A MEDICAL CORP",
            ", A MEDICAL CORPORATION",
            ", A MEDICAL PARTNERSHIP",
            ", A PROFESSIONAL MEDICAL CORPORATION",
            ", A RESTRICTED PROFESSIONAL BENEFIT COMPANY",
            ", A TEXAS LIMITED LIABILITY COMPANY",
            ", A.C.",
            ", A.S.",
            ", ACTIVIDAD AUXILIAR DEL CREDITO S.A. DE C.V.",
            ", ACTIVIDAD DEL CREDITO",
            ", ADMINISTRATION FOR THE BUILDING OF MOSQUES",
            ", AERONAUTICA",
            ", AKA TASOS",
            ", ALEXANDER",
            ", ALINA S",
            ", AL-JAHRA",
            ", AMRELI",
            ", AND ANIMAL WEALTH",
            ", AND BUJANOVAC",
            ", AND CONSULTANT GROUP",
            ", AND EXPORT OF HIGH TECH PRODUCTS ROSTEC",
            ", AND GENERAL SHIPPING LIMITED LIABILITY COMPANY",
            ", AND GENERAL SHIPPING LIMITED LIABILITY PRIVATE COMPANY",
            ", AND GENERAL SHIPPING/ LIMITED LIABILITY",
            ", AND RESEARCH",
            ", AND SECURITY SERVICES",
            ", AND STUDIES",
            ", AND TO CREATE SOCIETY - SIRAT",
            ", AO AKB",
            ", ARMANDO JIMENEZ",
            ", ARMANDO",
            ", ASOCIACION CIVIL",
            ", AUDITING",
            ", BANCO UNIVERSAL C.A.",
            ", BANCO UNIVERSAL CA",
            ", BANCO UNIVERSAL",
            ", BARRY DC",
            ", BEOGRAD STARI GRAD",
            ", BHR",
            ", BOSNIA AND HERZEGOVINA",
            ", BOYD",
            ", BRADFORD T MD PA",
            ", BRADY ISLAND FACILITY",
            ", BRIAN VALLERINO",
            ", BRIAN",
            ", C.A.",
            ", C.C.",
            ", C.S.W.",
            ", CANTU",
            ", CARL & DONALD INC",
            ", CASA DE CAMBIO",
            ", CHARLES E M D P",
            ", CHECHNYA (SOBR)",
            ", CHILD AND FAMILY SERVICES",
            ", CHINESE ACADEMY OF SCIENCES CAPITAL CONSTRUCTION",
            ", CHOW AND CHU",
            ", CIRCULARES Y ORTOGONALES",
            ", CJSC",
            ", CLINTON C. JR.",
            ", CLOSED JOINT-STOCK COMPANY",
            ", CO.",
            ", COMBUSTIBLES Y LUBRICANTES",
            ", CONCEPT",
            ", CORP.",
            ", CPA & ASSOCIATES",
            ", CPO",
            ", CRAIG",
            ", CRIMEA STATE AVIATION ENTERPRISE",
            ", CULTURAL",
            ", CULTURE AND BUILDING SOCIETY - SIRAT",
            ", D C",
            ", D D S",
            ", D M D",
            ", D O",
            ", D P M",
            ", D. C.",
            ", D. D. S.",
            ", D. O.",
            ", D.C.",
            ", D.D.D.",
            ", D.D.S.",
            ", D.M.D.",
            ", D.O.",
            ", D.P.M.",
            ", D.V.M.",
            ", D/B/A CULLIGAN OF SPRINGFIELD",
            ", DAVID",
            ", DBA DUNCAN DRUGS",
            ", DBA FAMILY CARE PHARMACY",
            ", DBA MIDAS",
            ", DBA NOBLE E&C",
            ", DDS",
            ", DE LA CLASE OBRERA",
            ", DEBORAH L",
            ", DEL",
            ", DELORES",
            ", DENNIS B DDS",
            ", DMD",
            ", DO",
            ", DOCHERNEE OBSHCHESTVO S OGRANICHENNOI OTVETSTVENNOSTYU",
            ", DON",
            ", DOUGLAS",
            ", DP",
            ", DPM P C",
            ", DPM",
            ", DR DON",
            ", DR WIT A INTERNAL MEDICINE",
            ", DR.",
            ", DRUG STORE",
            ", DUBAI",
            ", EDWIN AND ASSOCIATES",
            ", EDWIN AND EDWIN",
            ", ELECTRONICS & MEDIA PRINTING CO. LTD.",
            ", ENGINEERING",
            ", ENVIRONMENTAL",
            ", FACS",
            ", FELTON & MINKUS",
            ", FORMERLY KMCO PROPERTIES LP",
            ", FORMERLY KMTEX PROPERTIES",
            ", G. YEKATERINBURG OAO",
            ", G.EKATERINBURG",
            ", GANDHIDHAM",
            ", GARCIA",
            ", GENERAL TRADE",
            ", GEOFIZIKI I MINERALNOGO SYRYA",
            ", GERARD FRANCIS",
            ", GOA",
            ", GONDA",
            ", GP",
            ", GUARD AND SECURITY SERVICES",
            ", GUARDING AND SECURITY SERVICES",
            ", GUARDING",
            ", GUP RK",
            ", GUP",
            ", HAJI ABDUL BASEER MONEY CHANGER",
            ", I.G.",
            ", II",
            ", III BAYNARD",
            ", III",
            ", IN.",
            ", INC DBA GARRETT WAKATO OLUBO MSPT",
            ", INC DBA NOBLE E&C",
            ", INC",
            ", INC. (SCR)",
            ", INC. AKA FINCH HILL WATER COMPANY",
            ", INC. ALSO DBA RKB FACILITY SOLUTIONS",
            ", INC. D/B/A DIAL A MAID",
            ", INC. D/B/A ZIP IT DRY CLEANERS",
            ", INC. DBA CAPE COD ICE",
            ", INC. OF SUFFOLK",
            ", INC. RETIREMENT PLAN",
            ", INC.",
            ", INCORPORATED",
            ", INDIANA",
            ", INMOBILIARIA Y CONSTRUCCION DE OBRAS",
            ", INTER",
            ", INTL.",
            ", IRGC (PASDARAN)",
            ", ITS OFFICERS",
            ", IV",
            ", JEFFERSON A. AND JEFFERSON T.",
            ", JOINT STOCK COMPANY",
            ", JOINT-STOCK COMPANY",
            ", JOYCE",
            ", JR. GONZALEZ PIZANA",
            ", JR. M.D",
            ", JR.",
            ", JSC",
            ", K.K.",
            ", KEENAN R",
            ", KENNETH JAMES",
            ", KEVIN J",
            ", KRIMTETS",
            ", KRYMSKE RESPUBLIKANSKE PIDPRYEMSTVO",
            ", L L C",
            ", L. C.",
            ", L.C.",
            ", L.L.C",
            ", L.L.C.",
            ", L.P.",
            ", L.T.D.",
            ", LAW OFFICE OF",
            ", LESTER EARL EARL ANDERSON",
            ", LIMITED (D/B/A)",
            ", LIMITED LIABILITY COMPANY",
            ", LIMITED",
            ", LLC (GTS)",
            ", LLC (USA)",
            ", LLC D/B/A GREEN WORKS HOLDINGS",
            ", LLC DBA HEARNS ENTERPRISES",
            ", LLC DBA HUSSEY COPPER",
            ", LLC DBA MIDAS",
            ", LLC DBA NOLAN MANUFACTURING CO.",
            ", LLC DBA NOLAN MFG. CO. - ELECTRONICS DIVISION",
            ", LLC DBA VICTOR TORRES CONSTRUCTION",
            ", LLC USA",
            ", LLC",
            ", LLC)",
            ", LLC.",
            ", LLLP",
            ", LLP",
            ", LTD LCC",
            ", LTD",
            ", LTD. CHINA PINGMEI SHENMA GROUP",
            ", LTD. NANCHANG BRANCH",
            ", LTD.",
            ", LTD._IT DIVISION",
            ", M D",
            ", M S",
            ", M.D. AND ASSOCIATES",
            ", M.D. P.",
            ", M.D.",
            ", M.S.",
            ", MADHUBANI",
            ", MANUFACTURE",
            ", MD PA",
            ", MD PLLC",
            ", MD.",
            ", MDS",
            ", MEDIA",
            ", MEDICAL CO",
            ", MEDVEDJA",
            ", MERCADO EXTERIOR",
            ", MICHAEL A",
            ", MONTENEGRO",
            ", MUJER Y COMUNAS",
            ", MUJER Y COMUNIAS",
            ", MUMBAI",
            ", MUREADA",
            ", N.J.",
            ", NATIONAL PRODUCTION AND AGRARIAN UNION",
            ", NEW DELHI",
            ", NOSE AND THROAT",
            ", O.",
            ", OJSC",
            ", OOO",
            ", OPEN JOINT STOCK COMPANY",
            ", OPEN JOINT-STOCK COMPANY",
            ", ORANGE",
            ", ORTHOTIC & PEDORTHIC ASSOCIATES",
            ", OTKRYTOE AKTSIONERNOE OBSCHCHESTVO",
            ", OTKRYTOE AKTSIONERNOE OBSHCHESTVO",
            ", P A",
            ", P C",
            ", P",
            ", P. A.",
            ", P. C.",
            ", P.",
            ", P.A.",
            ", P.C. AND ASSOCIATES",
            ", P.C.",
            ", P.J.S.",
            ", P.L.C.",
            ", P.L.L.C.",
            ", P.S.",
            ", PA ",
            ", PARQUE DE SANTA MARIA HOUSING DEVELOPMENT",
            ", PC - SOUTHGATE",
            ", PC.",
            ", PH. D. PSYCHOLOGIST",
            ", PH.D",
            ", PH.D. AND ASSOCIATES",
            ", PH.D.",
            ", PIETRACK AND ASSOCIATES",
            ", PJSC (UKRAINE)",
            ", PJSC",
            ", PL.L.C.",
            ", PLC",
            ", PLLC",
            ", PPLC",
            ", PRODUCTION AND EXPORT OF ADVANCED TECHNOLOGY INDUSTRIAL PRODUCT ROSTEKHNOLOGII",
            ", PRODUCTION AND EXPORT OF ADVANCED TECHNOLOGY INDUSTRIAL PRODUCT",
            ", PROFESSIONAL ASSOCIATION",
            ", PROFESSIONAL CHIROPRACTIC CORPORATION",
            ", PROFESSIONAL DENTAL CORP.",
            ", PROMET I USLUGE MELVALE CORPORATION DOO",
            ", PROPAGANDA AND AGITATION DEPARTMENT",
            ", PRYVATNE AT",
            ", PUBLIC JOINT STOCK COMPANY",
            ", PUERTO RICO",
            ", R AND DC",
            ", R&DC",
            ", RALPH",
            ", RESEARCH",
            ", ROBERT D. AND ASSOCIATES",
            ", ROBERT T JR MD",
            ", ROSHELL",
            ", RUSSIAN ACADEMY OF SCIENCES",
            ", S C",
            ", S DE R.L. DE CV",
            ", S K MD INC",
            ", S. DE P.R. DE R.L. DE C.V.",
            ", S. DE P.R. DE R.L.",
            ", S. DE R.L. DE C.V.",
            ", S.A. (GTI)",
            ", S.A. DE C. V.",
            ", S.A. DE C.V",
            ", S.A. DE C.V. FARMACIA JERLYNE",
            ", S.A. DE C.V.",
            ", S.A.",
            ", S.A.C.",
            ", S.A.C.A.",
            ", S.A.P.I. DE C.V.",
            ", S.A.R.L.",
            ", S.C. DE R.L. DE C.V.",
            ", S.C.",
            ", S.P.R. DE R.I.",
            ", S.R.O.",
            ", SADRA",
            ", SC",
            ", SCOTT L",
            ", SERVICIOS Y MANTENIMIENTOS C.A.",
            ", SHARJAH",
            ", SOCIEDAD ANOMINA DE CAPITAL VARIABLE",
            ", SOCIEDAD ANONIMA DE CAPITAL VARIABLE",
            ", SOCIEDAD ANONIMA",
            ", SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA",
            ", SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA",
            ", SOCIETY OF THE REBIRTH OF THE ISLAMIC PEOPLE",
            ", SPINE SURGERY",
            ", SPRL",
            ", SR.",
            ", SRI LANKA",
            ", STATE RESEARCH AND PRODUCTION ENTERPRISE BAZALT",
            ", STEPHENS",
            ", SUBSIDIARIES AND DIVISIONS",
            ", SUPPORT AND PROCUREMENT KALA NAFT COMPANY",
            ", TAYLOR",
            ", TECNICOS Y OPERATIVOS DUREL",
            ", TOV",
            ", TRADE & INVESTMENT S.R.O.",
            ", TRADE AND GENERAL SERVICES LTD. / BAGHDAD",
            ", TRADE AND INVESTMENT S.R.O.",
            ", TRANSPORTATION & OIL SERVICES LTD.",
            ", TRANSPORTATION AND OIL SERVICES",
            ", TRANSPORTE",
            ", UCH",
            ", UP",
            ", V.Z.W.",
            ", VISAKHAPATNAM",
            ", W.L.L.",
            ", WENDALL ALAN",
            ", Y SERVICIOS AEREOS S.A. DE C.V.",
            ", YASIR RAFEA ALI",
            ", ZAKRYTOE AKTSIONERNOE OBSHCHESTVO INVESTITSIONNAYA KOMPANIYA",
            ",110016",
            ",271308",
            ",362720",
            ",364560",
            ",370201",
            ",400023",
            ",400053",
            ",403802",
            ",530026",
            ",ARE",
            ",INC.",
            ",IND",
            ",LLC",
            ",LTD.",
            ",OOO",
            ",P.A.",
            ",PLLC",
            "GPB-IPOTEKA OAO, AB",
            "BASTECKI CHIROPRACTIC, A",
            "DENTAL CENTER, A",
            "DENTAL CENTER, A, PC - SOUTHGATE",
            "GENTLE DENTAL HOMECARE GROUP, A",
            "LITTLE WALNUT PHARMACY, A",
            "INFOROS INFORMATION AGENCY, CO, LTD.",
            "ZAVOD FIOLENT, PAT",
            "ADEL PHYSICAL THERAPY, PC",
            "ADEL PHYSICAL THERAPY, PC",
            "ASSOCIATED PODIATRISTS, PC",
            "B. K. JOHNSON, PC",
            "CARDINAL RESPIRATORY, PC",
            "CARDINAL RESPIRATORY, PC",
            "CARESOUTH CLINIC, PC",
            "CARLOS H. POWERS,  DDS, PC",
            "CARLOS H. POWERS,  DDS, PC",
            "CONVENIENT DENTAL CARE CENTER, PC",
            "DENTAL CENTER, A, PC - SOUTHGATE",
            "DOWNTOWN MEDICAL, PC",
            "DOWNTOWN MEDICAL, PC",
            "DR WIT INTERNAL MEDICINE PROFESSIONAL GERIATRIC, PC",
            "DR. GOODMAN-CHERRIER, PC",
            "EDWARDO M YAMBO MD, PC",
            "EDWARDO M YAMBO, MD, PC",
            "ELM NEUROLOGICAL CARE, PC",
            "ELM NEUROLOGICAL CARE, PC",
            "EMERALD PHYSICAL THERAPY, PC",
            "EMERALD PHYSICAL THERAPY, PC",
            "FOWLERVILLE CHIROPRACTIC CLINC, PC",
            "FOWLERVILLE CHIROPRACTIC CLINC, PC",
            "HYLAND MEDICAL, PC",
            "HYLAND MEDICAL, PC",
            "ILLINOIS HEALTH CARE CLINIC, PC",
            "ILLINOIS HEALTH CARE CLINIC, PC",
            "INFINITE WELLNESS MEDICAL, PC",
            "JAMES D. C. JARAMILLO, MD., PC.",
            "JAMES D. C. JARAMILLO, MD., PC.",
            "JOHN J. MERENDINO, SR., MD., PC.",
            "JOHN J. MERENDINO, SR., MD., PC.",
            "JOHN R. MROZEK, MD, PC",
            "JOHN R. MROZEK, MD, PC",
            "JUST KIDZ DENTISTRY, PC",
            "LARRY L. KOMPUS, M.D., PC",
            "MANCEWICZ & WHITE, DDS, PC",
            "MARK W IZARD, MD, PC",
            "MARK W IZARD, MD, PC",
            "MED-AMERICA PHYSICIAN, PC",
            "MED-AMERICA PHYSICIAN, PC",
            "MEHRAN ZAMANI, DDS, PC",
            "MEHRAN ZAMANI, DDS, PC",
            "MICHAEL K. NUNN, PC",
            "MICHAEL T PARRA MD, PC",
            "OMNI MEDICAL, PC",
            "ROBERT F. KELISEK, DDS, PC",
            "ROBERT F. KELISEK, DDS, PC",
            "ROBERT T MORGAN, MD, PC",
            "VT-DENTAL CONCERNS, PC",
            "VT-DENTAL CONCERNS, PC",
            "SEACREST MARINE SERVICES PRIVATE LIMITED (675538576)- 37 BEACH ROAD , VISAKHAPATNAM , AP ,530026,IND",
            "UCHEBNY TSENTR ESHELON, ANO",
            "PEARL ENERGY SERVICES, SA",
            "REEM PHARMACEUTICAL, SAL"

    };

    public static final String[] replacementList = {
            " & STOVALL",
            " (F/K/A JONES FESTUS DEVELOPMENT",
            " A CALIFORNIA CORP",
            " A CHIROPRACTIC CORPORATION",
            " A CORPORATION",
            " A MEDICAL CORP",
            " A MEDICAL CORPORATION",
            " A MEDICAL PARTNERSHIP",
            " A PROFESSIONAL MEDICAL CORPORATION",
            " A RESTRICTED PROFESSIONAL BENEFIT COMPANY",
            " A TEXAS LIMITED LIABILITY COMPANY",
            " A.C.",
            " A.S.",
            " ACTIVIDAD AUXILIAR DEL CREDITO S.A. DE C.V.",
            " ACTIVIDAD DEL CREDITO",
            " ADMINISTRATION FOR THE BUILDING OF MOSQUES",
            " AERONAUTICA",
            " AKA TASOS",
            " ALEXANDER",
            " ALINA S",
            " AL-JAHRA",
            " AMRELI",
            " AND ANIMAL WEALTH",
            " AND BUJANOVAC",
            " AND CONSULTANT GROUP",
            " AND EXPORT OF HIGH TECH PRODUCTS ROSTEC",
            " AND GENERAL SHIPPING LIMITED LIABILITY COMPANY",
            " AND GENERAL SHIPPING LIMITED LIABILITY PRIVATE COMPANY",
            " AND GENERAL SHIPPING/ LIMITED LIABILITY",
            " AND RESEARCH",
            " AND SECURITY SERVICES",
            " AND STUDIES",
            " AND TO CREATE SOCIETY - SIRAT",
            " AO AKB",
            " ARMANDO JIMENEZ",
            " ARMANDO",
            " ASOCIACION CIVIL",
            " AUDITING",
            " BANCO UNIVERSAL C.A.",
            " BANCO UNIVERSAL CA",
            " BANCO UNIVERSAL",
            " BARRY DC",
            " BEOGRAD STARI GRAD",
            " BHR",
            " BOSNIA AND HERZEGOVINA",
            " BOYD",
            " BRADFORD T MD PA",
            " BRADY ISLAND FACILITY",
            " BRIAN VALLERINO",
            " BRIAN",
            " C.A.",
            " C.C.",
            " C.S.W.",
            " CANTU",
            " CARL & DONALD INC",
            " CASA DE CAMBIO",
            " CHARLES E M D P",
            " CHECHNYA (SOBR)",
            " CHILD AND FAMILY SERVICES",
            " CHINESE ACADEMY OF SCIENCES CAPITAL CONSTRUCTION",
            " CHOW AND CHU",
            " CIRCULARES Y ORTOGONALES",
            " CJSC",
            " CLINTON C. JR.",
            " CLOSED JOINT-STOCK COMPANY",
            " CO.",
            " COMBUSTIBLES Y LUBRICANTES",
            " CONCEPT",
            " CORP.",
            " CPA & ASSOCIATES",
            " CPO",
            " CRAIG",
            " CRIMEA STATE AVIATION ENTERPRISE",
            " CULTURAL",
            " CULTURE AND BUILDING SOCIETY - SIRAT",
            " D C",
            " D D S",
            " D M D",
            " D O",
            " D P M",
            " D. C.",
            " D. D. S.",
            " D. O.",
            " D.C.",
            " D.D.D.",
            " D.D.S.",
            " D.M.D.",
            " D.O.",
            " D.P.M.",
            " D.V.M.",
            " D/B/A CULLIGAN OF SPRINGFIELD",
            " DAVID",
            " DBA DUNCAN DRUGS",
            " DBA FAMILY CARE PHARMACY",
            " DBA MIDAS",
            " DBA NOBLE E&C",
            " DDS",
            " DE LA CLASE OBRERA",
            " DEBORAH L",
            " DEL",
            " DELORES",
            " DENNIS B DDS",
            " DMD",
            " DO",
            " DOCHERNEE OBSHCHESTVO S OGRANICHENNOI OTVETSTVENNOSTYU",
            " DON",
            " DOUGLAS",
            " DP",
            " DPM P C",
            " DPM",
            " DR DON",
            " DR WIT A INTERNAL MEDICINE",
            " DR.",
            " DRUG STORE",
            " DUBAI",
            " EDWIN AND ASSOCIATES",
            " EDWIN AND EDWIN",
            " ELECTRONICS & MEDIA PRINTING CO. LTD.",
            " ENGINEERING",
            " ENVIRONMENTAL",
            " FACS",
            " FELTON & MINKUS",
            " FORMERLY KMCO PROPERTIES LP",
            " FORMERLY KMTEX PROPERTIES",
            " G. YEKATERINBURG OAO",
            " G.EKATERINBURG",
            " GANDHIDHAM",
            " GARCIA",
            " GENERAL TRADE",
            " GEOFIZIKI I MINERALNOGO SYRYA",
            " GERARD FRANCIS",
            " GOA",
            " GONDA",
            " GP",
            " GUARD AND SECURITY SERVICES",
            " GUARDING AND SECURITY SERVICES",
            " GUARDING",
            " GUP RK",
            " GUP",
            " HAJI ABDUL BASEER MONEY CHANGER",
            " I.G.",
            " II",
            " III BAYNARD",
            " III",
            " IN.",
            " INC DBA GARRETT WAKATO OLUBO MSPT",
            " INC DBA NOBLE E&C",
            " INC",
            " INC. (SCR)",
            " INC. AKA FINCH HILL WATER COMPANY",
            " INC. ALSO DBA RKB FACILITY SOLUTIONS",
            " INC. D/B/A DIAL A MAID",
            " INC. D/B/A ZIP IT DRY CLEANERS",
            " INC. DBA CAPE COD ICE",
            " INC. OF SUFFOLK",
            " INC. RETIREMENT PLAN",
            " INC.",
            " INCORPORATED",
            " INDIANA",
            " INMOBILIARIA Y CONSTRUCCION DE OBRAS",
            " INTER",
            " INTL.",
            " IRGC (PASDARAN)",
            " ITS OFFICERS",
            " IV",
            " JEFFERSON A. AND JEFFERSON T.",
            " JOINT STOCK COMPANY",
            " JOINT-STOCK COMPANY",
            " JOYCE",
            " JR. GONZALEZ PIZANA",
            " JR. M.D",
            " JR.",
            " JSC",
            " K.K.",
            " KEENAN R",
            " KENNETH JAMES",
            " KEVIN J",
            " KRIMTETS",
            " KRYMSKE RESPUBLIKANSKE PIDPRYEMSTVO",
            " L L C",
            " L. C.",
            " L.C.",
            " L.L.C",
            " L.L.C.",
            " L.P.",
            " L.T.D.",
            " LAW OFFICE OF",
            " LESTER EARL EARL ANDERSON",
            " LIMITED (D/B/A)",
            " LIMITED LIABILITY COMPANY",
            " LIMITED",
            " LLC (GTS)",
            " LLC (USA)",
            " LLC D/B/A GREEN WORKS HOLDINGS",
            " LLC DBA HEARNS ENTERPRISES",
            " LLC DBA HUSSEY COPPER",
            " LLC DBA MIDAS",
            " LLC DBA NOLAN MANUFACTURING CO.",
            " LLC DBA NOLAN MFG. CO. - ELECTRONICS DIVISION",
            " LLC DBA VICTOR TORRES CONSTRUCTION",
            " LLC USA",
            " LLC",
            " LLC)",
            " LLC.",
            " LLLP",
            " LLP",
            " LTD LCC",
            " LTD",
            " LTD. CHINA PINGMEI SHENMA GROUP",
            " LTD. NANCHANG BRANCH",
            " LTD.",
            " LTD._IT DIVISION",
            " M D",
            " M S",
            " M.D. AND ASSOCIATES",
            " M.D. P.",
            " M.D.",
            " M.S.",
            " MADHUBANI",
            " MANUFACTURE",
            " MD PA",
            " MD PLLC",
            " MD.",
            " MDS",
            " MEDIA",
            " MEDICAL CO",
            " MEDVEDJA",
            " MERCADO EXTERIOR",
            " MICHAEL A",
            " MONTENEGRO",
            " MUJER Y COMUNAS",
            " MUJER Y COMUNIAS",
            " MUMBAI",
            " MUREADA",
            " N.J.",
            " NATIONAL PRODUCTION AND AGRARIAN UNION",
            " NEW DELHI",
            " NOSE AND THROAT",
            " O.",
            " OJSC",
            " OOO",
            " OPEN JOINT STOCK COMPANY",
            " OPEN JOINT-STOCK COMPANY",
            " ORANGE",
            " ORTHOTIC & PEDORTHIC ASSOCIATES",
            " OTKRYTOE AKTSIONERNOE OBSCHCHESTVO",
            " OTKRYTOE AKTSIONERNOE OBSHCHESTVO",
            " P A",
            " P C",
            " P",
            " P. A.",
            " P. C.",
            " P.",
            " P.A.",
            " P.C. AND ASSOCIATES",
            " P.C.",
            " P.J.S.",
            " P.L.C.",
            " P.L.L.C.",
            " P.S.",
            " PA ",
            " PARQUE DE SANTA MARIA HOUSING DEVELOPMENT",
            " PC - SOUTHGATE",
            " PC.",
            " PH. D. PSYCHOLOGIST",
            " PH.D",
            " PH.D. AND ASSOCIATES",
            " PH.D.",
            " PIETRACK AND ASSOCIATES",
            " PJSC (UKRAINE)",
            " PJSC",
            " PL.L.C.",
            " PLC",
            " PLLC",
            " PPLC",
            " PRODUCTION AND EXPORT OF ADVANCED TECHNOLOGY INDUSTRIAL PRODUCT ROSTEKHNOLOGII",
            " PRODUCTION AND EXPORT OF ADVANCED TECHNOLOGY INDUSTRIAL PRODUCT",
            " PROFESSIONAL ASSOCIATION",
            " PROFESSIONAL CHIROPRACTIC CORPORATION",
            " PROFESSIONAL DENTAL CORP.",
            " PROMET I USLUGE MELVALE CORPORATION DOO",
            " PROPAGANDA AND AGITATION DEPARTMENT",
            " PRYVATNE AT",
            " PUBLIC JOINT STOCK COMPANY",
            " PUERTO RICO",
            " R AND DC",
            " R&DC",
            " RALPH",
            " RESEARCH",
            " ROBERT D. AND ASSOCIATES",
            " ROBERT T JR MD",
            " ROSHELL",
            " RUSSIAN ACADEMY OF SCIENCES",
            " S C",
            " S DE R.L. DE CV",
            " S K MD INC",
            " S. DE P.R. DE R.L. DE C.V.",
            " S. DE P.R. DE R.L.",
            " S. DE R.L. DE C.V.",
            " S.A. (GTI)",
            " S.A. DE C. V.",
            " S.A. DE C.V",
            " S.A. DE C.V. FARMACIA JERLYNE",
            " S.A. DE C.V.",
            " S.A.",
            " S.A.C.",
            " S.A.C.A.",
            " S.A.P.I. DE C.V.",
            " S.A.R.L.",
            " S.C. DE R.L. DE C.V.",
            " S.C.",
            " S.P.R. DE R.I.",
            " S.R.O.",
            " SADRA",
            " SC",
            " SCOTT L",
            " SERVICIOS Y MANTENIMIENTOS C.A.",
            " SHARJAH",
            " SOCIEDAD ANOMINA DE CAPITAL VARIABLE",
            " SOCIEDAD ANONIMA DE CAPITAL VARIABLE",
            " SOCIEDAD ANONIMA",
            " SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA",
            " SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA",
            " SOCIETY OF THE REBIRTH OF THE ISLAMIC PEOPLE",
            " SPINE SURGERY",
            " SPRL",
            " SR.",
            " SRI LANKA",
            " STATE RESEARCH AND PRODUCTION ENTERPRISE BAZALT",
            " STEPHENS",
            " SUBSIDIARIES AND DIVISIONS",
            " SUPPORT AND PROCUREMENT KALA NAFT COMPANY",
            " TAYLOR",
            " TECNICOS Y OPERATIVOS DUREL",
            " TOV",
            " TRADE & INVESTMENT S.R.O.",
            " TRADE AND GENERAL SERVICES LTD. / BAGHDAD",
            " TRADE AND INVESTMENT S.R.O.",
            " TRANSPORTATION & OIL SERVICES LTD.",
            " TRANSPORTATION AND OIL SERVICES",
            " TRANSPORTE",
            " UCH",
            " UP",
            " V.Z.W.",
            " VISAKHAPATNAM",
            " W.L.L.",
            " WENDALL ALAN",
            " Y SERVICIOS AEREOS S.A. DE C.V.",
            " YASIR RAFEA ALI",
            " ZAKRYTOE AKTSIONERNOE OBSHCHESTVO INVESTITSIONNAYA KOMPANIYA",
            " 110016",
            " 271308",
            " 362720",
            " 364560",
            " 370201",
            " 400023",
            " 400053",
            " 403802",
            " 530026",
            " ARE",
            " INC.",
            " IND",
            " LLC",
            " LTD.",
            " OOO",
            " P.A.",
            " PLLC",
            "GPB-IPOTEKA OAO AB",
            "BASTECKI CHIROPRACTIC A",
            "DENTAL CENTER A",
            "DENTAL CENTER A PC - SOUTHGATE",
            "GENTLE DENTAL HOMECARE GROUP A",
            "LITTLE WALNUT PHARMACY A",
            "INFOROS INFORMATION AGENCY CO LTD.",
            "ZAVOD FIOLENT PAT",
            "ADEL PHYSICAL THERAPY PC",
            "ADEL PHYSICAL THERAPY PC",
            "ASSOCIATED PODIATRISTS PC",
            "B. K. JOHNSON PC",
            "CARDINAL RESPIRATORY PC",
            "CARDINAL RESPIRATORY PC",
            "CARESOUTH CLINIC PC",
            "CARLOS H. POWERS  DDS PC",
            "CARLOS H. POWERS  DDS PC",
            "CONVENIENT DENTAL CARE CENTER PC",
            "DENTAL CENTER A PC - SOUTHGATE",
            "DOWNTOWN MEDICAL PC",
            "DOWNTOWN MEDICAL PC",
            "DR WIT INTERNAL MEDICINE PROFESSIONAL GERIATRIC PC",
            "DR. GOODMAN-CHERRIER PC",
            "EDWARDO M YAMBO MD PC",
            "EDWARDO M YAMBO MD PC",
            "ELM NEUROLOGICAL CARE PC",
            "ELM NEUROLOGICAL CARE PC",
            "EMERALD PHYSICAL THERAPY PC",
            "EMERALD PHYSICAL THERAPY PC",
            "FOWLERVILLE CHIROPRACTIC CLINC PC",
            "FOWLERVILLE CHIROPRACTIC CLINC PC",
            "HYLAND MEDICAL PC",
            "HYLAND MEDICAL PC",
            "ILLINOIS HEALTH CARE CLINIC PC",
            "ILLINOIS HEALTH CARE CLINIC PC",
            "INFINITE WELLNESS MEDICAL PC",
            "JAMES D. C. JARAMILLO MD. PC.",
            "JAMES D. C. JARAMILLO MD. PC.",
            "JOHN J. MERENDINO SR. MD. PC.",
            "JOHN J. MERENDINO SR. MD. PC.",
            "JOHN R. MROZEK MD PC",
            "JOHN R. MROZEK MD PC",
            "JUST KIDZ DENTISTRY PC",
            "LARRY L. KOMPUS M.D. PC",
            "MANCEWICZ & WHITE DDS PC",
            "MARK W IZARD MD PC",
            "MARK W IZARD MD PC",
            "MED-AMERICA PHYSICIAN PC",
            "MED-AMERICA PHYSICIAN PC",
            "MEHRAN ZAMANI DDS PC",
            "MEHRAN ZAMANI DDS PC",
            "MICHAEL K. NUNN PC",
            "MICHAEL T PARRA MD PC",
            "OMNI MEDICAL PC",
            "ROBERT F. KELISEK DDS PC",
            "ROBERT F. KELISEK DDS PC",
            "ROBERT T MORGAN MD PC",
            "VT-DENTAL CONCERNS PC",
            "VT-DENTAL CONCERNS PC",
            "SEACREST MARINE SERVICES PRIVATE LIMITED (675538576)- 37 BEACH ROAD  VISAKHAPATNAM  AP 530026 IND",
            "UCHEBNY TSENTR ESHELON ANO",
            "PEARL ENERGY SERVICES SA",
            "REEM PHARMACEUTICAL SAL"
    };
}
